version: "3.8"
services:
  postgresdb:
    image: postgres:15-bookworm
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5431:5432"